"""Added system roles

Revision ID: 329210b1c496
Revises: f46612634117
Create Date: 2025-06-29 14:10:09.077300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "329210b1c496"
down_revision: Union[str, Sequence[str], None] = "f46612634117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "roles",
        "description",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )

    roles_table = sa.table('roles',
                           sa.column('name', sa.String),
                           sa.column('description', sa.String)
                           )

    op.bulk_insert(
        roles_table,
        [
            {'name': 'admin', 'description': 'Administrator role'},
            {'name': 'user', 'description': 'Default user role'},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles WHERE name IN ('user', 'admin')")

    op.alter_column(
        "roles",
        "description",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    ),
    # ### end Alembic commands ###
